import { Inter } from 'next/font/google'
import './globals.css'
import CustomProvider from '../lib/CustomProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Develop by vijay',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomProvider>{children}</CustomProvider>
      </body>
    </html>
  );
}
